apiVersion: v1
kind: Service
metadata:
  name: myapp-test-service
  labels:
    app: apache
spec:
  type: NodePort
  selector:
    app: apache
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007